    version: '3.5'
    
    services:
      postgres:
        image: postgres:latest
        environment:
          POSTGRES_USER: ADMIN
          POSTGRES_PASSWORD: ADMIN
          PGDATA: /data/postgres
        volumes:
          - postgres:/data/postgres
          - ./initdb:/docker-entrypoint-initdb.d 
        ports:
          - "5432:5432"
        networks:
          - postgres
        restart: unless-stopped

    chroma:
      image: chromadb/chroma
      ports:
        - "8000:8000"
      volumes:
        - chroma:/data/chroma
      networks:
        - chroma
      restart: unless-stopped

    networks:
      postgres:
        driver: bridge
      chroma:
         driver: bridge
    
    volumes:
        postgres:
        chroma:
